es:
  host: http://localhost:59200
  index: ods_material_rizhao_price
  progress_index: ods_rizhao_price_progress
  sync_log_index: ods_rizhao_price_sync_log
site:
  base_url: http://58.59.43.227:81/EpointSDRZ
  price_page: http://58.59.43.227:81/dist/#/index/priceDissemination
sync:
  last_period: 2026-04
